PipelineSecrets:
  DockerConfig: '{"auths":{"ubidy.azurecr.io":{"auth":"dWJpZHk6aFV0OXNDUFg1MzlMT1doWmo0M0F0MWpJakUrQWdVZHk="}}}'
cleanup:
  Annotations:
    helm.sh/hook: pre-delete
    helm.sh/hook-delete-policy: hook-succeeded
  Args:
  - --cleanup
controllerbuild: {}
expose:
  Annotations:
    helm.sh/hook: post-install,post-upgrade
    helm.sh/hook-delete-policy: hook-succeeded
  Args:
  - --v
  - 4
  config:
    domain: 52.187.228.252.nip.io
    exposer: Ingress
    http: "true"
jenkins:
  Servers:
    Global:
      EnvVars:
        DOCKER_REGISTRY: ubidy.azurecr.io
        TILLER_NAMESPACE: kube-system
prow: {}
